# docker-compose.yml
version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: oscarVenturenixLab2023.
      MYSQL_DATABASE: docker
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
  demo-junit-test:
    image: demo-junit-test:0.0.2
    build:
      context: ./demo-junit-test
      dockerfile: Dockerfile
    ports:
      - 8183:8083
  demo-jmeter-test:
    image: demo-jmeter-test:0.0.2
    build:
      context: ./demo-jmeter-test
      dockerfile: Dockerfile
    ports:
      - 8184:8084
  redis:
    image: redis:latest
    ports:
      - "6379:6379"